// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5wbrg9ZJC2zR2aQMeBDL8y3KMwpNwK-g',
    appId: '1:461456300473:web:a7497bfd2feca4bb807e68',
    messagingSenderId: '461456300473',
    projectId: 'tabi-chat-app-1ff51',
    authDomain: 'tabi-chat-app-1ff51.firebaseapp.com',
    storageBucket: 'tabi-chat-app-1ff51.appspot.com',
    measurementId: 'G-CBSRV2FFCH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtCVuYRb6sFHR_dXZ3lphKygS3l_ZyDuA',
    appId: '1:461456300473:android:7b0305361d750490807e68',
    messagingSenderId: '461456300473',
    projectId: 'tabi-chat-app-1ff51',
    storageBucket: 'tabi-chat-app-1ff51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT2QxKbJBZK7M3S6S1J5Iz4Sn541t8i2E',
    appId: '1:461456300473:ios:28d07aa5631b86b1807e68',
    messagingSenderId: '461456300473',
    projectId: 'tabi-chat-app-1ff51',
    storageBucket: 'tabi-chat-app-1ff51.appspot.com',
    iosClientId: '461456300473-6uneub6416lc6mm0dkdvrp4rub1hmnde.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT2QxKbJBZK7M3S6S1J5Iz4Sn541t8i2E',
    appId: '1:461456300473:ios:28d07aa5631b86b1807e68',
    messagingSenderId: '461456300473',
    projectId: 'tabi-chat-app-1ff51',
    storageBucket: 'tabi-chat-app-1ff51.appspot.com',
    iosClientId: '461456300473-6uneub6416lc6mm0dkdvrp4rub1hmnde.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
