name: chat_app
description: A Mobile Dev Final project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.1+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter_launcher_icons: ^0.9.3
  photo_view: ^0.14.0
  cached_network_image: ^3.2.1
  geoflutterfire: ^3.0.3
  geocoding: ^2.0.4
  geolocator: ^8.2.1
  cloud_firestore: ^3.1.17
  firebase_auth: ^3.3.18
  firebase_core: ^1.17.0
  firebase_storage: ^10.2.16
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get_it: ^7.2.0
  intl: ^0.17.0
  modal_bottom_sheet: ^2.0.1
  image_picker: ^0.8.5+3
  flutter_native_splash: ^2.2.3
  flutter_statusbarcolor_ns: ^0.4.0
  username_gen: ^1.0.4
  change_app_package_name: ^1.1.0

flutter_native_splash:
  image: assets/images/tabi_lightmode.png
  color: "#f9f9f9"
  image_dark: assets/images/tabi_darkmode.png
  color_dark: "#000000"
  ios: true

dev_dependencies:
  flutter_launcher_icons: "^0.9.2"
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/tabi_lightmode.png"

flutter_app_name:
  name: "Tabi Tabi"
flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
